language: haskell
install:
  - "cabal install --dry-run -v3 --enable-tests"
  - "travis_retry cabal install --force-reinstalls --enable-tests"
notifications:
  email:
    recipients: travis@silk.co
    on_success: never
    on_failure: change
